version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_oop_tasks
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "composer install && php index.php"

  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_oop_tasks_test
    volumes:
      - .:/app
    working_dir: /app
    command: composer test
